### ISSUE TITLE
demo crash

### ISSUE THREAD

**Issue by csjlengxiang** [faimin/ZDTableViewBinding#3]

**Comment by faimin** [comment]
@csjlengxiang 谢谢反馈，已修复。这是 [UITableView+FDTemplateLayoutCell](https://github.com/forkingdog/UITableView-FDTemplateLayoutCell) 在10.2系统下存在 [bug #257](https://github.com/forkingdog/UITableView-FDTemplateLayoutCell/issues/257)导致的，现在临时的解决办法是尽量避免添加大于等于或者小于等于之类的约束
